[[drop_modifiers]]
id = "showcase:precision_mode/quartz_yield"
blocks = ["tag:c:ores/quartz"]
drops = ["minecraft:quartz"]
tools = ["tag:minecraft:pickaxes"]
multiply = 1.1
priority = 900
exclusive = true
