[[grants]]
id = "showcase:grant_advancement_husbandry/tactical_fishing_1"
repeat = "once"
scope = "player"
condition = { type = "advancement", id = "minecraft:husbandry/tactical_fishing", count = 1 }
