[[grants]]
id = "showcase:grant_kill_enderman_32"
repeat = "once"
scope = "player"
condition = { type = "kill", id = "minecraft:enderman", count = 32 }

[rewards]
items = ["minecraft:amethyst_shard:16"]
xp_levels = 8
