[[grants]]
id = "showcase:grant_kill_ravager_3"
repeat = "once"
scope = "player"
condition = { type = "kill", id = "minecraft:ravager", count = 3 }

[rewards]
items = ["minecraft:diamond:4"]
xp_levels = 8
