#Xaero's World Map
[xaeroworldmap]
	Enable = true
	SkipVanillaColorCheck = true

#Xaero's Minimap
[xaerominimap]
	Enable = true
	SkipVanillaColorCheck = true

#Diagonal Blocks
[diagonalblocks]
	Enable = true
	fence = true
	wall = true
