[[grants]]
id = "showcase:grant_kill_wither_1"
repeat = "once"
scope = "player"
condition = { type = "kill", id = "minecraft:wither", count = 1 }

[rewards]
items = ["minecraft:nether_star:1"]
xp_levels = 10
