[[grants]]
id = "showcase:grant_kill_with_skeleton_bow_20"
repeat = "once"
scope = "player"
condition = { type = "kill_with_item", id = "minecraft:skeleton", with = "minecraft:bow", count = 20 }

[rewards]
items = ["minecraft:arrow:32"]
xp_levels = 2
